version: "3.7"

services:
  watchtower:
    container_name: watchtower
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.dev-self-contained
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    command: --interval 10 --http-api-metrics --http-api-token demotoken --debug prometheus grafana parent child
  prometheus:
    container_name: prometheus
    image: prom/prometheus@sha256:63805ebb8d2b3920190daf1cb14a60871b16fd38bed42b857a3182bc621f4996
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus/
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana@sha256:b5b59bfc7561634c2d7b136c4543d702ebcc94a3da477f21ff26f89ffd4214fa
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
  parent:
    image: nginx@sha256:f5c017fb33c6db484545793ffb67db51cdd7daebee472104612f73a85063f889
    container_name: parent
  child:
    image: nginx:alpine@sha256:6e39bb3765ac959c7e1240509636173417a5e37abf140f418401e2fa73970bbe
    labels:
      com.centurylinklabs.watchtower.depends-on: parent
    container_name: child

volumes:
  prometheus: {}
  grafana: {}
